# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  opts,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.kernelParams = ["nohibernate"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c2507f11-d97b-4ceb-8bc3-15e7f5b8953b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6111-BE56";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/5dde3f85-e5b9-4286-a180-eade534798bb";
    fsType = "ext4";
  };

  fileSystems."/mnt/data2" = {
    device = "/dev/disk/by-uuid/86ab48f6-2469-4eb2-afe1-88daf1bd9a11";
    fsType = "ext4";
  };

  swapDevices = [];

  networking = {
    useDHCP = lib.mkDefault false;
    hostId = "0ec79991";
    # consider moving to systemd.network.netdev
    interfaces = {
      enp90s0 = {
        useDHCP = lib.mkDefault true;
        ipv4 = {
          addresses = [
            {
              address = opts.lanAddress;
              prefixLength = 24;
            }
          ];
        };
      };
      wlan0 = {
        useDHCP = lib.mkDefault true;
      };
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

	hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    opengl.enable = true;
		graphics.enable = true;
		# nvidia-container-toolkit = {
    #   enable = true;
    #   mount-nvidia-executables = true;
    # };
		nvidia = {
      # Enable modesetting
      modesetting.enable = true;

      # Enable the NVIDIA persistence daemon (optional but recommended)
      nvidiaPersistenced.enable = true;

      # Use the latest NVIDIA driver package
      package = config.boot.kernelPackages.nvidiaPackages.latest;

      # Enable the NVIDIA Container Toolkit
      nvidiaContainerToolkit.enable = true;
    };
	};
}
