---
# Homepage configuration
# See https://fontawesome.com/v6/search for icon options

title: "Athena-zero dashboard"
subtitle: "Nothing Limited"
logo: "assets/tools/athena.png"
# icon: "fas fa-owl" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">\u2764\ufe0f</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default

stylesheet:
  - "assets/custom.css"

# Optional theme customization (color overrides)
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/tools/wallpaper-light.jpeg"
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/tools/wallpaper.jpeg"

# Optional navbar
links:
  - name: "github.com/joegiralt/dot"
    icon: "fab fa-github"
    url: "https://github.com/joegiralt/dot"
    target: "_blank"

# Services
services:
  - name: "Media"
    icon: "fas fa-photo-film" # free FA6 icon
    items:
      - name: "Plex"
        logo: "assets/tools/plex.jpg"
        subtitle: "Media Client"
        url: "https://plex.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Kavita"
        logo: "assets/tools/kavita.avif"
        subtitle: "Books Management"
        url: "https://kavita.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        subtitle: "Self Hosted Media Client"
        url: "https://jellyfin.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Audiobookshelf"
        logo: "assets/tools/audiobookshelf.svg"
        subtitle: "Audiobooks & Podcasts"
        url: "https://abs.nothing.ltd"
        tag: "app"
        target: "_blank"

  - name: "Applications"
    icon: "fas fa-layer-group"
    items:
      - name: "Nextcloud"
        logo: "assets/tools/logo_nextcloud.svg"
        subtitle: "Our Personal Cloud"
        url: "https://nextcloud.nothing.ltd"
        tag: "app"
        target: "_blank"
        type: Nextcloud
      - name: "Jellyseerr"
        logo: "assets/tools/jellyfin.png"
        subtitle: "Media Management"
        url: "https://jellyseer.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Ollama Interface"
        logo: "assets/tools/ollama.png"
        subtitle: "AI Model Management Interface"
        url: "https://ollama.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Livebook"
        logo: "assets/tools/livebook.png"
        subtitle: "Elixir Collaborative Code Notebook"
        url: "https://livebook.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Archive Warrior"
        logo: "assets/tools/warrior-logo.png"
        subtitle: "Crowd-powered web archiving appliance"
        url: "https://archive-warrior.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Paperless"
        logo: "assets/tools/paperless.png"
        subtitle: "Document Management"
        url: "https://paperless.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Stirling PDF"
        logo: "assets/tools/stirling.svg"
        subtitle: "PDF Utility Tool"
        url: "https://stirling-pdf.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Qbittorrent"
        logo: "assets/tools/qbittorrent.png"
        subtitle: "Torrenter"
        url: "https://qbt.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        subtitle: "Film Collection Manager"
        url: "https://radarr.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Readarr"
        logo: "assets/tools/readarr.avif"
        subtitle: "Books Searching & Indexing"
        url: "https://readarr.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Prowlarr"
        logo: "assets/tools/prowlarr.avif"
        subtitle: "Indexers Management"
        url: "https://prowlarr.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.avif"
        subtitle: "TV Searching & Indexing"
        url: "https://sonarr.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Lidarr"
        logo: "assets/tools/lidarr.png"
        subtitle: "Music Searching & Indexing"
        url: "https://lidarr.nothing.ltd"
        tag: "app"
        target: "_blank"

  - name: "Monitoring & Utilities"
    icon: "fas fa-screwdriver-wrench"
    items:
      - name: "Portainer"
        logo: "assets/tools/portainer.svg"
        subtitle: "Advanced Container Monitoring"
        url: "https://portainer.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "VS Code"
        logo: "assets/tools/vscode.svg"
        subtitle: "Web-Based Code Editor"
        url: "https://code.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Filebrowser"
        logo: "assets/tools/filebrowser.svg"
        subtitle: "Web-Based FileSystem"
        url: "https://filebrowser.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Uptime Kuma"
        logo: "assets/tools/uptime-kuma.svg"
        subtitle: "Monitoring & Uptime Tool"
        url: "https://uptime-kuma.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Data Visualization & Monitoring"
        url: "https://grafana.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "Nginx Proxy Manager"
        logo: "assets/tools/nginx.png"
        subtitle: "Web Server Management"
        url: "https://nginx.nothing.ltd"
        tag: "app"
        target: "_blank"
      - name: "AdGuard"
        logo: "assets/tools/adguard.png"
        subtitle: "Network-wide Ad Blocking"
        url: "https://adguard.nothing.ltd"
        tag: "app"
        target: "_blank"
#  - name: "Applications"
#    icon: "fas fa-layer-group"
#    items:
#      - name: "Bazarr"
#        logo: "assets/tools/bazarr.png"
#        subtitle: "Subtitles Automation"
#        url: "https://bazarr.nothing.ltd"
#        tag: "app"
#        target: "_blank"
#      - name: "Tdarr"
#        logo: "assets/tools/tdarr.png"
#        subtitle: "Transcode/Optimize Library"
#        url: "https://tdarr.nothing.ltd"
#        tag: "app"
#        target: "_blank"

#  - name: "Monitoring & Utilities"
#    icon: "fas fa-screwdriver-wrench"
#    items:
#      - name: "Prometheus"
#        logo: "assets/tools/prometheus.svg"
#        subtitle: "Metrics Source"
#        url: "http
